### PR TITLE
Add Jetson Orin Nano provisioning support

### PR DESCRIPTION
**Pull request by acostach**
As of right now the Orin Nano Devkit image is available in the staging environment

### CODE REVIEW

**Comment by dremsol** [comment]
flashing the device using custom flasher image `build/tmp/deploy/images/jetson-orin-nano-devkit-nvme/balena-image-flasher-jetson-orin-nano-devkit-nvme.balenaos-img` results in following error.

```bash
rm: cannot remove '/usr/src/app/orin-flash//orin_nano/Linux_for_Tegra/bootloader/boot0.img': No such file or directory
[LOG] Kernel image has been extracted and the BSP kernel has been replaced with the one in balenaOS
###############################################################################
# L4T BSP Information:
# R35 , REVISION: 3.1
# User release: 0.0
./flash.sh: line 1705: /usr/src/app/orin-flash/orin_nano/Linux_for_Tegra/rootfs/etc/user_release_version: No such file or directory
###############################################################################
copying emc_fuse_dev_params(/usr/src/app/orin-flash/orin_nano/Linux_for_Tegra/bootloader/t186ref/BCT/tegra234-br-bct-diag-boot.dts)... done.
copying device_config(/usr/src/app/orin-flash/orin_nano/Linux_for_Tegra/bootloader/t186ref/BCT/tegra234-mb1-bct-device-p3767-0000.dts)... done.
copying misc_config(/usr/src/app/orin-flash/orin_nano/Linux_for_Tegra/bootloader/t186ref/BCT/tegra234-mb1-bct-misc-p3767-0000.dts)... done.
./tegraflash.py --chip 0x23 --applet "/usr/src/app/orin-flash/orin_nano/Linux_for_Tegra/bootloader/mb1_t234_prod.bin" --skipuid --cfg readinfo_t234_min_prod.xml --dev_params tegra234-br-bct-diag-boot.dts --device_config tegra234-mb1-bct-device-p3767-0000.dts --misc_config tegra234-mb1-bct-misc-p3767-0000.dts --bins "mb2_applet applet_t234.bin" --cmd "dump eeprom cvm cvm.bin; dump custinfo custinfo_out.bin; reboot recovery"
Welcome to Tegra Flash
version 1.0.0
Type ? or help for help and q or quit to exit
Use ! to execute system commands

[   0.0483 ] tegrarcm_v2 --chip 0x23 0 --ismb2applet
[   0.0505 ] File rcm_state open failed
[   0.0506 ] ERROR: failed to read rcm_state
[   0.0506 ]
[   0.0524 ] tegrasign_v3.py --key None --getmode mode.txt
[   0.0531 ] Assuming zero filled SBK key
[   0.0523 ] Pre-processing config: tegra234-mb1-bct-device-p3767-0000.dts
[   0.0603 ] Pre-processing config: tegra234-mb1-bct-misc-p3767-0000.dts
[   0.0703 ] Parsing partition layout
[   0.0718 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0739 ] Kernel DTB used: None
[   0.0740 ] WARNING: dce base dtb is not provided

[   0.0740 ] Parsing partition layout
[   0.0753 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0771 ] Creating list of images to be signed
[   0.0785 ] tegrahost_v2 --chip 0x23 0 --partitionlayout readinfo_t234_min_prod.xml.bin --list images_list.xml zerosbk
[   0.0799 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
[   0.0821 ] Header already present for mb1_t234_prod_aligned_sigheader.bin
[   0.0831 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
[   0.0891 ] Header already present for mb1_t234_prod_aligned_sigheader.bin
[   0.0908 ] MB1: Nvheader already present is psc_bl1_t234_prod_aligned.bin
[   0.0957 ] Header already present for psc_bl1_t234_prod_aligned_sigheader.bin
[   0.0970 ] adding BCH for mb2_t234_aligned.bin
[   0.0987 ] MB1: Nvheader already present is psc_bl1_t234_prod_aligned.bin
[   0.1100 ] Header already present for psc_bl1_t234_prod_aligned_sigheader.bin
[   0.1111 ] adding BCH for mb2_t234_aligned.bin
[   0.1258 ] Filling MB1 storage info
[   0.1259 ] Parsing dev params for multi chains
[   0.1327 ] Generating br-bct
[   0.1340 ] Updating dev and MSS params in BR BCT
[   0.1341 ] tegrabct_v2 --dev_param tegra234-br-bct-diag-boot_cpp.dtb --brbct br_bct.cfg --chip 0x23 0
[   0.1359 ] Updating bl info
[   0.1373 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updateblinfo readinfo_t234_min_prod.xml.bin
[   0.1384 ] WARNING: boot chain is not completed. set to 0
[   0.1397 ] Generating signatures
[   0.1414 ] tegrasign_v3.py --key None --list images_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1418 ] Assuming zero filled SBK key
[   0.1586 ] Warning: pub_key.key is not found
[   0.1577 ] Parsing dev params for multi chains
[   0.1577 ] Generating br-bct
[   0.1592 ] Updating dev and MSS params in BR BCT
[   0.1593 ] tegrabct_v2 --dev_param tegra234-br-bct-diag-boot_cpp.dtb --brbct br_bct.cfg --chip 0x23 0
[   0.1605 ] Updating bl info
[   0.1615 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updateblinfo readinfo_t234_min_prod.xml.bin --updatesig images_list_signed.xml
[   0.1624 ] WARNING: boot chain is not completed. set to 0
[   0.1635 ] Get Signed section of bct
[   0.1649 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --listbct bct_list.xml
[   0.1663 ] Signing BCT
[   0.1680 ] tegrasign_v3.py --key None --list bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1683 ] Assuming zero filled SBK key
[   0.1713 ] Sha saved in br_bct_BR.sha
[   0.1717 ] Warning: pub_key.key is not found
[   0.1702 ] Updating BCT with signature
[   0.1712 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updatesig bct_list_signed.xml
[   0.1720 ] Offset :4608 Len :3584
[   0.1726 ] Generating SHA2 Hash
[   0.1742 ] tegrasign_v3.py --key None --list bct_list.xml --sha sha512
[   0.1745 ] Assuming zero filled SBK key
[   0.1746 ] Assuming zero filled SBK key
[   0.1775 ] Sha saved in br_bct_BR.sha
[   0.1763 ] Updating BCT with SHA2 Hash
[   0.1776 ] tegrabct_v2 --brbct br_bct_BR.bct --chip 0x23 0 --updatesha bct_list_signed.xml
[   0.1788 ] Offset :4608 Len :3584
[   0.1792 ] Offset :68 Len :8124
[   0.1798 ] Generating coldboot mb1-bct
[   0.1813 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_cold_boot_bct.cfg --misc tegra234-mb1-bct-misc-p3767-0000_cpp.dtb --device tegra234-mb1-bct-device-p3767-0000_cpp.dtb
[   0.1828 ] MB1-BCT version: 0.10
[   0.1832 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1845 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1847 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.1848 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1848 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1848 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.1848 ] ERROR: /misc/tsc_controls/tsc_locking_config is not supported
[   0.1848 ] ERROR: /misc/tsc_controls/tsc_locking_diff_configuration is not supported
[   0.1848 ] ERROR: /misc/tsc_controls/tsc_locking_ref_frequency_configuration is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_locking_control is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_configuration is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_locking_fast_adjust_configuration is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_delta_control is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_capture_control_ptx is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_capture_config_ptx is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_stscrsr is not supported
[   0.1849 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_num_control is not supported
[   0.1849 ]
[   0.1849 ] Parsing config file :tegra234-mb1-bct-device-p3767-0000_cpp.dtb
[   0.1849 ] Added Platform Config 9 data with size :- 100
[   0.1849 ]
[   0.1850 ] Updating mb1-bct with firmware information
[   0.1861 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_cold_boot_bct_MB1.bct --updatefwinfo readinfo_t234_min_prod.xml.bin
[   0.1889 ] tegrahost_v2 --chip 0x23 0 --align mb1_cold_boot_bct_MB1_aligned.bct
[   0.1908 ] tegrahost_v2 --chip 0x23 0 --magicid MBCT --appendsigheader mb1_cold_boot_bct_MB1_aligned.bct zerosbk
[   0.1918 ] adding BCH for mb1_cold_boot_bct_MB1_aligned.bct
[   0.1944 ] tegrasign_v3.py --key None --list mb1_cold_boot_bct_MB1_aligned_sigheader.bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.1947 ] Assuming zero filled SBK key
[   0.1972 ] Warning: pub_key.key is not found
[   0.1974 ] tegrahost_v2 --chip 0x23 0 --updatesigheader mb1_cold_boot_bct_MB1_aligned_sigheader.bct.encrypt mb1_cold_boot_bct_MB1_aligned_sigheader.bct.hash zerosbk
[   0.1990 ] Generating recovery mb1-bct
[   0.2003 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_bct.cfg --misc tegra234-mb1-bct-misc-p3767-0000_cpp.dtb --device tegra234-mb1-bct-device-p3767-0000_cpp.dtb
[   0.2017 ] MB1-BCT version: 0.10
[   0.2021 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.2035 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.2035 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_UNUSED5/ is not supported
[   0.2035 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.2035 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.2035 ] ERROR: carveout /misc/carveout/aux_info@CARVEOUT_MCE_COVERAGE/ is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_config is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_diff_configuration is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_ref_frequency_configuration is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_control is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_configuration is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_fast_adjust_configuration is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_delta_control is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_capture_control_ptx is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_capture_config_ptx is not supported
[   0.2035 ] ERROR: /misc/tsc_controls/tsc_stscrsr is not supported
[   0.2036 ] ERROR: /misc/tsc_controls/tsc_locking_adjust_num_control is not supported
[   0.2036 ]
[   0.2036 ] Parsing config file :tegra234-mb1-bct-device-p3767-0000_cpp.dtb
[   0.2036 ] Added Platform Config 9 data with size :- 100
[   0.2036 ]
[   0.2037 ] Updating mb1-bct with firmware information
[   0.2046 ] tegrabct_v2 --chip 0x23 0 --mb1bct mb1_bct_MB1.bct --recov --updatefwinfo readinfo_t234_min_prod.xml.bin
[   0.2086 ] tegrahost_v2 --chip 0x23 0 --align mb1_bct_MB1_aligned.bct
[   0.2108 ] tegrahost_v2 --chip 0x23 0 --magicid MBCT --appendsigheader mb1_bct_MB1_aligned.bct zerosbk
[   0.2116 ] adding BCH for mb1_bct_MB1_aligned.bct
[   0.2141 ] tegrasign_v3.py --key None --list mb1_bct_MB1_aligned_sigheader.bct_list.xml --pubkeyhash pub_key.key --sha sha512
[   0.2143 ] Assuming zero filled SBK key
[   0.2164 ] Warning: pub_key.key is not found
[   0.2166 ] tegrahost_v2 --chip 0x23 0 --updatesigheader mb1_bct_MB1_aligned_sigheader.bct.encrypt mb1_bct_MB1_aligned_sigheader.bct.hash zerosbk
[   0.2185 ] Error: Skip generating mem_bct because sdram_config is not defined
[   0.2186 ] Error: Skip generating mem_bct because sdram_config is not defined
[   0.2186 ] Copying signatures
[   0.2202 ] tegrahost_v2 --chip 0x23 0 --partitionlayout readinfo_t234_min_prod.xml.bin --updatesig images_list_signed.xml
[   0.2269 ] mb1_t234_prod_aligned_sigheader.bin.encrypt filename is from images_list
[   0.2271 ] psc_bl1_t234_prod_aligned_sigheader.bin.encrypt filename is from images_list
[   0.2271 ] Boot Rom communication
[   0.2282 ] tegrarcm_v2 --new_session --chip 0x23 0 --uid --download bct_br br_bct_BR.bct --download mb1 mb1_t234_prod_aligned_sigheader.bin.encrypt --download psc_bl1 psc_bl1_t234_prod_aligned_sigheader.bin.encrypt --download bct_mb1 mb1_bct_MB1_sigheader.bct.encrypt
[   0.2291 ] BR_CID: 0x80012344705DD45F5C00000004030240
[   0.2319 ] Sending bct_br
[   0.2323 ] ERROR: might be timeout in USB write.
Error: Return value 3
Command tegrarcm_v2 --new_session --chip 0x23 0 --uid --download bct_br br_bct_BR.bct --download mb1 mb1_t234_prod_aligned_sigheader.bin.encrypt --download psc_bl1 psc_bl1_t234_prod_aligned_sigheader.bin.encrypt --download bct_mb1 mb1_bct_MB1_sigheader.bct.encrypt
Reading board information failed.

```

**Comment by acostach** [comment]
Any chance you could try from a Linux host?

**Comment by dremsol** [comment]
Tried again today after updating `usbipd` and managed to get it working with following command from windows host `usbipd wsl attach -ab 1-1`. 

Seems that the procedure has succeeded following the process as described in the readme. However, can seem to access over ssh although the device gets an ip-address. I've build the image with following command so it should be a development image allowing ssh access. 
```bash
./balena-yocto-scripts/build/balena-build.sh -d jetson-orin-nano-devkit-nvme -s /var/cache/yocto/ -k -g "--build-history -d -r --rm-work"
```

**Comment by acostach** [comment]
lgtm

**Pull request merged**
