### PR TITLE
Add support for TX2 4GB device.

### PR DESCRIPTION
**Pull request by smithandrewc**

### CODE REVIEW

**Comment by acostach** [comment]
@smithandrewc changes seem fine, please add a "Change-type: patch" and a "Signed-off-by: You <your@email.com>" to the commit message

**Comment by smithandrewc** [comment]
> @smithandrewc changes seem fine, please add a "Change-type: patch" and a "Signed-off-by: You <[your@email.com](mailto:your@email.com)>" to the commit message

Done, thanks.

**Comment by acostach** [comment]
@balena-ci retest

**Comment by acostach** [comment]
Thanks for the PR @smithandrewc, I included your commit in https://github.com/balena-os/jetson-flash/pull/50

**Pull request closed without merging**
